version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://skillz.scaloz.com/api
    container_name: skillz-frontend
    ports:
      - "8080:80"

    env_file:
      - ./frontend/.env

    depends_on:
      - server

    restart: always

    networks:
      - skillz-network

  server:
    build: ./server
    container_name: skillz-backend

    ports:
      - "5000:5000"

    env_file:
      - ./server/.env

    restart: always

    networks:
      - skillz-network

networks:
  skillz-network:
    driver: bridge
