import jwt from 'jsonwebtoken';
import { AUTH_CONFIG } from '../config/security.js';

/**
 * JWT Utility
 * Handles token generation and verification using centralized config.
 *
 * Verification tries two secrets in order:
 *  1. SCALOZ_JWT_SECRET — tokens minted by the Scaloz Workspace SSO backend
 *  2. JWT_SECRET        — tokens minted locally by this Skillz server
 *
 * This means SSO tokens from Scaloz pass, AND locally-generated tokens still work.
 */
export const generateToken = (userId, tenantId, roleIds, managerId = null, domainId = null, tokenVersion = 1) => {
    try {
        if (!userId) {
            throw new Error('UserId is required to generate a token');
        }

        return jwt.sign(
            { userId, tenantId, roleIds, managerId, domainId, tokenVersion },
            AUTH_CONFIG.JWT_SECRET,
            { expiresIn: AUTH_CONFIG.JWT_EXPIRES_IN }
        );
    } catch (error) {
        console.error('Error generating JWT:', error.message);
        throw error;
    }
};

export const verifyToken = (token) => {
    if (!token) return null;

    // Try each accepted secret in priority order.
    // Scaloz SSO tokens are tried first; locally-minted Skillz tokens are tried second.
    const secrets = [
        AUTH_CONFIG.SCALOZ_JWT_SECRET, // SSO tokens from Scaloz Workspace
        AUTH_CONFIG.JWT_SECRET,         // Tokens generated by this server
    ].filter(Boolean); // remove nulls/undefined in case env var is not set

    for (const secret of secrets) {
        try {
            const decoded = jwt.verify(token, secret);
            return decoded; // valid — return decoded payload immediately
        } catch (error) {
            // TokenExpiredError is a definitive failure regardless of secret — re-throw
            if (error.name === 'TokenExpiredError') {
                console.error('JWT Verification Error: token has expired');
                return null;
            }
            // InvalidSignatureError just means this secret is wrong — try the next one
        }
    }

    // No secret matched
    console.error('JWT Verification Error: token signature does not match any known secret');
    return null;
};

/**
 * Decode token without verification (useful for logging/debugging)
 */
export const decodeToken = (token) => {
    return jwt.decode(token);
};
